---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: e2e-windows
spec:
  description: |
    An integration test which provisions a windows desktop machine to run e2e. 

    We need an azure account and a az blob to store the state of the infra.

  params:
    - name: SNAPSHOT 
      description: Snapshot of the application
      default: '{"components": [{"name":"test-app", "containerImage": "quay.io/example/repo:latest"}]}'
      type: string
    - name: secret-az-credentials
      description: |
        ocp secret holding the azure credentials. Secret should be accessible to this task.

        ---
        apiVersion: v1
        kind: Secret
        metadata:
          name: ${name}
        type: Opaque
        data:
          tenant_id: ${tenant_id}
          subscription_id: ${subscription_id}
          client_id: ${client_id}
          client_secret: ${client_secret}
          storage_account: ${storage_account}
          storage_key: ${storage_key}
          blob: ${blob}
      default: az-crcqe-bot
      type: string

  tasks:
    - name: init
      taskSpec:
        description: create correlation for the pipelinerun
        results:
          - name: correlation
        steps:
          - name: init
            image: registry.access.redhat.com/ubi9/ubi-minimal@sha256:ba0d97dd43fea58f9bdcc4488c60a3869827e1e30a51c11bbfae3fb7dc91e6f5
            script: |
              #!/bin/sh
              echo -n $RANDOM$RANDOM | tee $(results.correlation.path)
    - name: provision-windows
      runAfter:
        - init
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/adrianriobo/mapt
          - name: revision
            value: fix-329
          - name: pathInRepo
            value: tkn/infra-azure-windows-desktop.yaml
      params:
        - name: secret-az-credentials
          value: az-crcqe-bot
        - name: id
          value: $(tasks.init.results.correlation)
        - name: operation
          value: create
        - name: ownerKind
          value: 'PipelineRun'
        - name: ownerName
          value: $(context.pipelineRun.name)
        - name: ownerUid
          value: $(context.pipelineRun.uid)
        - name: tags
          value: 'cicd=konflux,pipelinerun=$(context.pipelineRun.name)'
  finally:
    - name: decommission-windows
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/adrianriobo/mapt
          - name: revision
            value: fix-329
          - name: pathInRepo
            value: tkn/infra-azure-windows-desktop.yaml
      params:
        - name: secret-az-credentials
          value: az-crcqe-bot
        - name: id
          value: $(tasks.init.results.correlation)
        - name: operation
          value: destroy
        - name: ownerKind
          value: 'PipelineRun'
        - name: ownerName
          value: $(context.pipelineRun.name)
        - name: ownerUid
          value: $(context.pipelineRun.uid)